/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Dao.AvaliarDao;
import Dao.CadastrarDao;
import Dao.UserDao;
import br.com.senac.servicostreaming.model.Avaliacaom;
import br.com.senac.servicostreaming.model.Conteudo;
import br.com.senac.servicostreaming.model.Usuario;
import javax.swing.JOptionPane;


/**
 *
 * @author Duwann
 */
public class Avaliacao extends javax.swing.JFrame {

    private Usuario usuario;
    
    public Avaliacao() {
        initComponents();
    }
    
     public Avaliacao(Usuario u) {
         
        initComponents();
        this.usuario = u;
        configurarBotoesPorTipoUsuario(usuario);
        
        if (usuario != null) {
           lblUsuario.setText(usuario.getNome());
       } else {
           lblUsuario.setText("Usuário não identificado");
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnAvaliacoes = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        btnPacotes = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNota = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        lblImagem3 = new javax.swing.JLabel();
        txtId2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnAvaliar = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnCadastro = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 39, 52));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("SansSerif", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Avaliações");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 110, -1));

        txtId.setBackground(new java.awt.Color(51, 51, 51));
        txtId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setToolTipText("Informe o id do conteúdo");
        txtId.setNextFocusableComponent(btnPesquisar);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 190, 30));

        btnAvaliacoes.setBackground(new java.awt.Color(24, 61, 128));
        btnAvaliacoes.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnAvaliacoes.setForeground(new java.awt.Color(255, 255, 255));
        btnAvaliacoes.setText("Avaliações");
        btnAvaliacoes.setContentAreaFilled(false);
        btnAvaliacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvaliacoesActionPerformed(evt);
            }
        });
        jPanel1.add(btnAvaliacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 120, 20));

        btnHome.setBackground(new java.awt.Color(24, 61, 128));
        btnHome.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Home");
        btnHome.setContentAreaFilled(false);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 100, 20));

        btnLista.setBackground(new java.awt.Color(24, 61, 128));
        btnLista.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnLista.setForeground(new java.awt.Color(255, 255, 255));
        btnLista.setText("Lista");
        btnLista.setContentAreaFilled(false);
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });
        jPanel1.add(btnLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 80, 20));

        btnPacotes.setBackground(new java.awt.Color(24, 61, 128));
        btnPacotes.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnPacotes.setForeground(new java.awt.Color(255, 255, 255));
        btnPacotes.setText("Pacotes");
        btnPacotes.setContentAreaFilled(false);
        btnPacotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacotesActionPerformed(evt);
            }
        });
        jPanel1.add(btnPacotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 120, 20));

        jLabel6.setFont(new java.awt.Font("SansSerif", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pesquisar por Id:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nota:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        txtNota.setBackground(new java.awt.Color(51, 51, 51));
        txtNota.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNota.setForeground(new java.awt.Color(255, 255, 255));
        txtNota.setToolTipText("Informe a nota do conteúdo(de 1 a 5)");
        txtNota.setNextFocusableComponent(btnAvaliar);
        txtNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNotaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 320, 30));

        btnPesquisar.setBackground(new java.awt.Color(24, 61, 128));
        btnPesquisar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setToolTipText("Botão para pesquisar pelo id");
        btnPesquisar.setNextFocusableComponent(txtNota);
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, 30));

        lblImagem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/0e65d4a0-5271-4bd6-9ed0-a43e6f529604.jpg"))); // NOI18N
        jPanel1.add(lblImagem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 530, 30));

        txtId2.setEditable(false);
        txtId2.setBackground(new java.awt.Color(51, 51, 51));
        txtId2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtId2.setForeground(new java.awt.Color(204, 204, 204));
        txtId2.setToolTipText("Id do conteúdo");
        txtId2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 320, 30));

        jLabel8.setFont(new java.awt.Font("SansSerif", 2, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Id:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        btnAvaliar.setBackground(new java.awt.Color(24, 61, 128));
        btnAvaliar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnAvaliar.setForeground(new java.awt.Color(255, 255, 255));
        btnAvaliar.setText("Avaliar");
        btnAvaliar.setToolTipText("Botão para enviar a sua nota");
        btnAvaliar.setNextFocusableComponent(txtId);
        btnAvaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvaliarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAvaliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 80, 30));

        txtNome.setEditable(false);
        txtNome.setBackground(new java.awt.Color(51, 51, 51));
        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNome.setForeground(new java.awt.Color(204, 204, 204));
        txtNome.setToolTipText("Nome do conteúdo");
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 320, 30));

        jLabel9.setFont(new java.awt.Font("SansSerif", 2, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nome:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        btnCadastro.setBackground(new java.awt.Color(24, 61, 128));
        btnCadastro.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnCadastro.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastro.setText("Cadastrar Conteúdos");
        btnCadastro.setContentAreaFilled(false);
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 210, 20));

        lblUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnAvaliacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvaliacoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAvaliacoesActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        
        Home home = new Home(usuario);
        home.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        
        Lista lista = new Lista(usuario);
        lista.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnListaActionPerformed

    private void btnPacotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacotesActionPerformed
        
        Pacote pacote = new Pacote(usuario);
        pacote.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnPacotesActionPerformed

    private void txtNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNotaActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
       if(!ValidacaoID()) {
         return;   
       }
        
       int idPesquisa = Integer.parseInt(txtId.getText());
        
        AvaliarDao dao = new AvaliarDao();
        Conteudo conteudo = dao.getConteudoId(idPesquisa);
        
        if(conteudo==null){
            JOptionPane.showMessageDialog(null,"Conteúdo não encontrado");
        }
        else{
            txtId2.setText(String.valueOf(conteudo.getId()));
            txtNome.setText(conteudo.getTitulo());
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtId2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId2ActionPerformed

    private void btnAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvaliarActionPerformed
        if (!ValidacaoDados()) {
        return;  
        }
        
        int id = Integer.parseInt(txtId.getText());
        int nota = Integer.parseInt(txtNota.getText());
        
        UserDao userDao = new UserDao();
        CadastrarDao cadastrarDao = new CadastrarDao();
        AvaliarDao dao = new AvaliarDao();
        
        int idUsuario = usuario.getId();
        
        Usuario usuario = userDao.buscarPorId(idUsuario);
        Conteudo conteudo = cadastrarDao.buscarPorId(id);
        
        Avaliacaom avaliacaom = new Avaliacaom();
        
        avaliacaom.setNota(nota);
        avaliacaom.setConteudo(conteudo);
        avaliacaom.setUsuario(usuario);
        
        dao.atualizar(avaliacaom);
        
        JOptionPane.showMessageDialog(null,"Atualização feita com sucesso");
        
        txtId.setText("");
        txtId2.setText("");
        txtNome.setText("");
        txtNota.setText("");
        
    }//GEN-LAST:event_btnAvaliarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        
        CadastrarS cadastrarS = new CadastrarS(usuario);
        cadastrarS.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Avaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Avaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Avaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Avaliacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Avaliacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvaliacoes;
    private javax.swing.JButton btnAvaliar;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnPacotes;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImagem3;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtId2;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNota;
    // End of variables declaration//GEN-END:variables

    public void configurarBotoesPorTipoUsuario(Usuario u) {
    
    if (u.getTipo().equalsIgnoreCase("Administrador")) {
        btnCadastro.setEnabled(true);
    } else if (u.getTipo().equalsIgnoreCase("usuario")) {
        btnCadastro.setEnabled(false);
        btnCadastro.setVisible(false);
    } else {
       
        btnCadastro.setVisible(false);
        btnCadastro.setEnabled(false);
    }
 }
    
    private boolean ValidacaoDados() {
         
       boolean notaB = txtNota.getText().matches("[0-5]");
         
        try {
            if (txtNota.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "⚠ Preencha todos os campos.","Erro", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            
            if (notaB == false) {
                javax.swing.JOptionPane.showMessageDialog(null, "⚠️ Nota só vai de 1 a 5 e não pode conter letras\n", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
                return false;
            }
            

        } catch (Exception e) {
            // Tratamento genérico para outros erros inesperados
            javax.swing.JOptionPane.showMessageDialog(this, "Ocorreu um erro: " + e.getMessage(), "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }
    
    private boolean ValidacaoID() {
    try {
        // Verifica se o campo está vazio
        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "⚠ O campo ID não pode estar vazio.", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        // Verifica se o ID contém apenas números
        try {
            int id = Integer.parseInt(txtId.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "⚠ O ID deve conter apenas números.", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Ocorreu um erro: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    return true;
}

}
