/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Dao.UserDao;
import Persistence.Criptografia;
import br.com.senac.servicostreaming.model.Usuario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Duwann
 */
public class Cadastro extends javax.swing.JFrame {

     List<Usuario> usuarios = new ArrayList<>();
     
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblImagem1 = new javax.swing.JLabel();
        lblImagem2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtConfirmarSenha = new javax.swing.JPasswordField();
        txtSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(26, 26, 26));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("SansSerif", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("mantenha-se conectado!");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 2, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Já se cadastrou ?");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Senha:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, -1, 20));

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail.setToolTipText("Insira um email(exemplo@gmail.com)");
        txtEmail.setNextFocusableComponent(txtSenha);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 260, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, -1, 20));

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 0, 0));
        btnLogin.setText("Login");
        btnLogin.setToolTipText("Botão para a tela de login");
        btnLogin.setNextFocusableComponent(txtNome);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 90, 30));

        btnCadastrar.setBackground(new java.awt.Color(24, 61, 128));
        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setToolTipText("Botão de cadastro");
        btnCadastrar.setNextFocusableComponent(btnLogin);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, 120, 30));

        jLabel5.setFont(new java.awt.Font("SansSerif", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Junte-se a nós!");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, -1, -1));

        lblImagem1.setBackground(new java.awt.Color(24, 61, 128));
        lblImagem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/d0f6973a-fb35-4b2f-a591-6be500acbdcd.jpg"))); // NOI18N
        jPanel1.add(lblImagem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 430, -1));

        lblImagem2.setBackground(new java.awt.Color(24, 61, 128));
        lblImagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/d0f6973a-fb35-4b2f-a591-6be500acbdcd.jpg"))); // NOI18N
        jPanel1.add(lblImagem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 420, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Confirmar Senha:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, -1, 20));

        txtNome.setBackground(new java.awt.Color(255, 255, 255));
        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNome.setToolTipText("Insira o seu nome de usuário");
        txtNome.setNextFocusableComponent(txtEmail);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 260, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Usuário:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, -1, 20));

        txtConfirmarSenha.setBackground(new java.awt.Color(255, 255, 255));
        txtConfirmarSenha.setToolTipText("Insira a mesma senha");
        txtConfirmarSenha.setNextFocusableComponent(btnCadastrar);
        txtConfirmarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConfirmarSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(txtConfirmarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 260, 30));

        txtSenha.setBackground(new java.awt.Color(255, 255, 255));
        txtSenha.setToolTipText("Insira uma senha(mínimo 4 caracteres)");
        txtSenha.setNextFocusableComponent(txtConfirmarSenha);
        jPanel1.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 260, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
       
        if(!ValidacaoDados()){
            return; 
        }
       UserDao dao = new UserDao();
       Usuario user = new Usuario();
       user.setNome(txtNome.getText());
       user.setEmail(txtEmail.getText());
       user.setSenha(Criptografia.getMD5(txtSenha.getText()));
       String Confirmar = txtConfirmarSenha.getText();
       
        if (!Confirmar.equals(txtSenha.getText())) {

            JOptionPane.showMessageDialog(null, "⚠ As senhas não coincidem. Por favor, tente novamente.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;  // Interrompe o processo se as senhas não coincidirem
        }
        
        int status = dao.cadastrar(user);
       
        if (status > 0) {
        txtEmail.setText("");
        txtSenha.setText("");
        txtConfirmarSenha.setText("");
        txtNome.setText("");
        JOptionPane.showMessageDialog(null, "✅ Usuário cadastrado com sucesso!", "Sucesso",
        JOptionPane.INFORMATION_MESSAGE);
       }
        else{  
            JOptionPane.showMessageDialog(null, "❌ Erro ao cadastrar usuário.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
        dao.desconectar();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtConfirmarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmarSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmarSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImagem1;
    private javax.swing.JLabel lblImagem2;
    private javax.swing.JPasswordField txtConfirmarSenha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

  
    private boolean ValidacaoDados() {

    boolean emailValido = txtEmail.getText().matches("^[\\w.-]+@[a-zA-Z\\d.-]+\\.[a-zA-Z]{2,}$");

    try {
       
        if (txtNome.getText().isEmpty() ||
            txtEmail.getText().isEmpty() ||
            String.valueOf(txtSenha.getPassword()).isEmpty() ||
            String.valueOf(txtConfirmarSenha.getPassword()).isEmpty()) {

            JOptionPane.showMessageDialog(null, "⚠ Preencha todos os campos.", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (!txtNome.getText().matches("[a-zA-Z0-9_]+")) {
            JOptionPane.showMessageDialog(null, "⚠ O nome de usuário só pode conter letras, números e _.","Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (!emailValido) {
            JOptionPane.showMessageDialog(null, "⚠ Email inválido! Use um formato válido (exemplo@dominio.com).", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        if (String.valueOf(txtSenha.getPassword()).length() < 4) {
            JOptionPane.showMessageDialog(null, "⚠ A senha deve ter no mínimo 4 caracteres.", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (!String.valueOf(txtSenha.getPassword()).equals(String.valueOf(txtConfirmarSenha.getPassword()))) {
            JOptionPane.showMessageDialog(null, "⚠ As senhas não coincidem!", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Ocorreu um erro: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    return true;
}

}
