/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Conexao.Conexao;
import Dao.CadastrarDao;
import Dao.UserDao;
import br.com.senac.servicostreaming.model.Conteudo;
import br.com.senac.servicostreaming.model.Usuario;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;


/**
 *
 * @author Duwann
 */
public class CadastrarS extends javax.swing.JFrame {

    private Usuario usuario;
    
    public CadastrarS() {
        initComponents();
    }

    CadastrarS(Usuario u) {  
        initComponents();
        this.usuario = u;  
        configurarBotoesPorTipoUsuario(usuario);
        
        if (usuario != null) {
           lblUsuario.setText(usuario.getNome());
       } else {
           lblUsuario.setText("Usuário não identificado");
       }
    }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        txtDescricao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEpisodios = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblImagem3 = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        btnAvaliacoes = new javax.swing.JButton();
        btnCadastro = new javax.swing.JButton();
        btnPacotes1 = new javax.swing.JButton();
        cboxTipo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 39, 52));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("SansSerif", 2, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Adicione novos conteúdos ao sistema.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 410, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Autor:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, 20));

        txtAutor.setBackground(new java.awt.Color(51, 51, 51));
        txtAutor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAutor.setForeground(new java.awt.Color(255, 255, 255));
        txtAutor.setToolTipText("Insira o autor");
        txtAutor.setNextFocusableComponent(txtDescricao);
        txtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorActionPerformed(evt);
            }
        });
        jPanel1.add(txtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 410, 30));

        txtData.setBackground(new java.awt.Color(51, 51, 51));
        txtData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtData.setForeground(new java.awt.Color(255, 255, 255));
        txtData.setToolTipText("Insira a data ( dd/mm/aaaa)");
        txtData.setNextFocusableComponent(txtAutor);
        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });
        jPanel1.add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 410, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Data de lançamento:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, 20));

        btnCadastrar.setBackground(new java.awt.Color(24, 61, 128));
        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setToolTipText("Botão para cadastrar o conteúdo");
        btnCadastrar.setNextFocusableComponent(txtNome);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 120, 30));

        txtDescricao.setBackground(new java.awt.Color(51, 51, 51));
        txtDescricao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDescricao.setForeground(new java.awt.Color(255, 255, 255));
        txtDescricao.setToolTipText("Insira uma descrição");
        txtDescricao.setNextFocusableComponent(cboxTipo);
        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });
        jPanel1.add(txtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 410, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Descrição");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, 20));

        txtEpisodios.setBackground(new java.awt.Color(51, 51, 51));
        txtEpisodios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEpisodios.setForeground(new java.awt.Color(255, 255, 255));
        txtEpisodios.setToolTipText("Insira a quantidade de episódios ou capítulos");
        txtEpisodios.setNextFocusableComponent(txtData);
        txtEpisodios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEpisodiosActionPerformed(evt);
            }
        });
        jPanel1.add(txtEpisodios, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 410, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Quantidade de episódios:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tipo:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, -1, 20));

        txtNome.setBackground(new java.awt.Color(51, 51, 51));
        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNome.setForeground(new java.awt.Color(255, 255, 255));
        txtNome.setToolTipText("Insira o nome do conteúdo");
        txtNome.setNextFocusableComponent(txtEpisodios);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 410, 30));

        lblImagem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/0e65d4a0-5271-4bd6-9ed0-a43e6f529604.jpg"))); // NOI18N
        jPanel1.add(lblImagem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 530, 30));

        btnHome.setBackground(new java.awt.Color(24, 61, 128));
        btnHome.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Home");
        btnHome.setContentAreaFilled(false);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 100, 20));

        btnLista.setBackground(new java.awt.Color(24, 61, 128));
        btnLista.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnLista.setForeground(new java.awt.Color(255, 255, 255));
        btnLista.setText("Lista");
        btnLista.setContentAreaFilled(false);
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });
        jPanel1.add(btnLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 80, 20));

        btnAvaliacoes.setBackground(new java.awt.Color(24, 61, 128));
        btnAvaliacoes.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnAvaliacoes.setForeground(new java.awt.Color(255, 255, 255));
        btnAvaliacoes.setText("Avaliações");
        btnAvaliacoes.setContentAreaFilled(false);
        btnAvaliacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvaliacoesActionPerformed(evt);
            }
        });
        jPanel1.add(btnAvaliacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 120, 20));

        btnCadastro.setBackground(new java.awt.Color(24, 61, 128));
        btnCadastro.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnCadastro.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastro.setText("Cadastrar Conteúdos");
        btnCadastro.setContentAreaFilled(false);
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 210, 20));

        btnPacotes1.setBackground(new java.awt.Color(24, 61, 128));
        btnPacotes1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnPacotes1.setForeground(new java.awt.Color(255, 255, 255));
        btnPacotes1.setText("Pacotes");
        btnPacotes1.setContentAreaFilled(false);
        btnPacotes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacotes1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPacotes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 120, 20));

        cboxTipo.setBackground(new java.awt.Color(51, 51, 51));
        cboxTipo.setForeground(new java.awt.Color(255, 255, 255));
        cboxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anime", "Filme", "Série", "Livro" }));
        cboxTipo.setToolTipText("Informe de qual tipo o conteúdo é");
        cboxTipo.setNextFocusableComponent(btnCadastrar);
        jPanel1.add(cboxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 140, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nome:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, 20));

        lblUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorActionPerformed

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        if (!ValidacaoDados()) {
        return;  
        }
        
        UserDao dao2 = new UserDao();
        Conteudo conteudo = new Conteudo();
        CadastrarDao dao = new CadastrarDao();
        Conexao c = new Conexao();
        java.sql.Connection status = c.conectar();
        int resposta;
        
        conteudo.setTipoConteudo(cboxTipo.getSelectedItem().toString());
        conteudo.setTitulo(txtNome.getText());
        conteudo.setQuantiEpisodios(Integer.parseInt(txtEpisodios.getText()));
        conteudo.setDataLancamento(txtData.getText());
        conteudo.setAutor(txtAutor.getText());
        conteudo.setDescricao(txtDescricao.getText());
        
        if (status == null) {
            JOptionPane.showMessageDialog(null, "Erro de conexão");
        }  {
            resposta = dao.salvar(conteudo);
            if (resposta == 1) {
                JOptionPane.showMessageDialog(null, "Dados incluidos com sucesso");
            } else if (resposta == 1062) {
                JOptionPane.showMessageDialog(null, "Filme já foi cadastrada");
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao tentar inserir dados");
            }
            
            dao2.desconectar();
        } 
        
        txtEpisodios.setText("");
        txtData.setText("");
        txtAutor.setText("");
        txtNome.setText("");
        txtDescricao.setText("");
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void txtEpisodiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEpisodiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEpisodiosActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
       
        Home home = new Home(usuario);
        home.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        
        Lista lista = new Lista(usuario);
        lista.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnListaActionPerformed

    private void btnAvaliacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvaliacoesActionPerformed
        
        Avaliacao avaliacao = new Avaliacao(usuario);
        avaliacao.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnAvaliacoesActionPerformed

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void btnPacotes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacotes1ActionPerformed
        
        Pacote pacote = new Pacote(usuario);
        pacote.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnPacotes1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvaliacoes;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnPacotes1;
    private javax.swing.JComboBox<String> cboxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImagem3;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtEpisodios;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables

     private boolean ValidacaoDados() {
         
       boolean dataB = txtData.getText().matches("[0-9]{2}[/][0-9]{2}[/][0-9]{4}");
       String autorB = txtAutor.getText();
         
        try {
            if (txtNome.getText().isEmpty() || txtEpisodios.getText().isEmpty() || txtData.getText().isEmpty() || txtAutor.getText().isEmpty() || txtDescricao.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "⚠ Preencha todos os campos.","Erro", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            
            try {
                int numeroEp = Integer.parseInt(txtEpisodios.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "⚠️ O Número de Episódios deve conter apenas números!", "Erro", JOptionPane.ERROR_MESSAGE);
                return false;
            }
            
            if (dataB == false) {
                javax.swing.JOptionPane.showMessageDialog(null, "⚠️ Data precisa ser no formato dd/mm/aaaa e não pode conter letras\n", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
                return false;
            }
            
            if (autorB.matches(".*\\d.*")) {
                javax.swing.JOptionPane.showMessageDialog(null, "⚠ Nome do autor não pode conter números", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
                return false;
            }
            

        } catch (Exception e) {
            // Tratamento genérico para outros erros inesperados
            javax.swing.JOptionPane.showMessageDialog(this, "Ocorreu um erro: " + e.getMessage(), "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }
  
    public void configurarBotoesPorTipoUsuario(Usuario u) {
    
    if (u.getTipo().equalsIgnoreCase("Administrador")) {
        btnCadastro.setEnabled(true);
    } else if (u.getTipo().equalsIgnoreCase("usuario")) {
        btnCadastro.setEnabled(false);
        btnCadastro.setVisible(false);
    } else {
       
        btnCadastro.setVisible(false);
        btnCadastro.setEnabled(false);
    }
 } 
     
}
