/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Conexao.Conexao;
import Dao.SugestaoDao;
import br.com.senac.servicostreaming.model.Sugestao;
import br.com.senac.servicostreaming.model.Usuario;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Duwann
 */
public class Home extends javax.swing.JFrame {
    
     private Usuario usuario; 
     private DefaultTableModel model;
    
    public Home() {
        initComponents();
    }

   public Home(Usuario u) {
        initComponents();
        model = (DefaultTableModel) tblSugestoes.getModel();
        this.usuario = u;
        configurarBotoesPorTipoUsuario(usuario);
        
        if (usuario != null) {
           lblUsuario.setText(usuario.getNome());
       } else {
           lblUsuario.setText("Usuário não identificado");
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtSugestoes = new javax.swing.JTextField();
        lblmagem = new javax.swing.JLabel();
        btnAvaliacoes = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        btnPacotes = new javax.swing.JButton();
        lblImagem2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSugestoes = new javax.swing.JTable();
        btnCadastro = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 39, 52));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("SansSerif", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("sugestões");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 90, -1));

        txtSugestoes.setBackground(new java.awt.Color(51, 51, 51));
        txtSugestoes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSugestoes.setForeground(new java.awt.Color(255, 255, 255));
        txtSugestoes.setToolTipText("Insira a sua sugestão");
        txtSugestoes.setNextFocusableComponent(btnEnviar);
        txtSugestoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSugestoesActionPerformed(evt);
            }
        });
        jPanel1.add(txtSugestoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 550, 30));

        lblmagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/adb923cd-358d-418c-aaf1-46da4641c54d.jpg"))); // NOI18N
        jPanel1.add(lblmagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 800, 120));

        btnAvaliacoes.setBackground(new java.awt.Color(24, 61, 128));
        btnAvaliacoes.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnAvaliacoes.setForeground(new java.awt.Color(255, 255, 255));
        btnAvaliacoes.setText("Avaliações");
        btnAvaliacoes.setContentAreaFilled(false);
        btnAvaliacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvaliacoesActionPerformed(evt);
            }
        });
        jPanel1.add(btnAvaliacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 120, 20));

        btnEnviar.setBackground(new java.awt.Color(24, 61, 128));
        btnEnviar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviar.setText("Enviar");
        btnEnviar.setToolTipText("Botão para enviar a sua sugestão");
        btnEnviar.setNextFocusableComponent(txtSugestoes);
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 80, 30));

        btnHome.setBackground(new java.awt.Color(24, 61, 128));
        btnHome.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Home");
        btnHome.setContentAreaFilled(false);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 100, 20));

        btnLista.setBackground(new java.awt.Color(24, 61, 128));
        btnLista.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnLista.setForeground(new java.awt.Color(255, 255, 255));
        btnLista.setText("Lista");
        btnLista.setContentAreaFilled(false);
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });
        jPanel1.add(btnLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 80, 20));

        btnPacotes.setBackground(new java.awt.Color(24, 61, 128));
        btnPacotes.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnPacotes.setForeground(new java.awt.Color(255, 255, 255));
        btnPacotes.setText("Pacotes");
        btnPacotes.setContentAreaFilled(false);
        btnPacotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacotesActionPerformed(evt);
            }
        });
        jPanel1.add(btnPacotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 120, 20));

        lblImagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/0e65d4a0-5271-4bd6-9ed0-a43e6f529604.jpg"))); // NOI18N
        jPanel1.add(lblImagem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 530, 30));

        tblSugestoes.setForeground(new java.awt.Color(70, 73, 75));
        tblSugestoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id da sugestão", "Nome", "Data e Hora", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSugestoes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 780, 210));

        btnCadastro.setBackground(new java.awt.Color(24, 61, 128));
        btnCadastro.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnCadastro.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastro.setText("Cadastrar Conteúdos");
        btnCadastro.setContentAreaFilled(false);
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 210, 20));

        lblUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSugestoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSugestoesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSugestoesActionPerformed

    private void btnAvaliacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvaliacoesActionPerformed
        
        Avaliacao avaliacao = new Avaliacao(usuario);
        avaliacao.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnAvaliacoesActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
       
        if(txtSugestoes.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"⚠ Nada escrito no campo de sugestões","Erro", JOptionPane.ERROR_MESSAGE);
            return ;
        }
        
        SugestaoDao dao = new SugestaoDao();
        Conexao c = new Conexao();
        java.sql.Connection status = c.conectar();
       
        if (status == null) {
            JOptionPane.showMessageDialog(null, "Erro de conexão");
        } 
        
        dao.addSugestao(usuario.getId(),usuario.getNome(),txtSugestoes.getText());
        atualizarTabela();
        
        txtSugestoes.setText("");
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        
        Lista lista = new Lista(usuario);
        lista.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnListaActionPerformed

    private void btnPacotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacotesActionPerformed
        
        Pacote pacote = new Pacote(usuario);
        pacote.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnPacotesActionPerformed

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        
        CadastrarS cadastrarS = new CadastrarS(usuario);
        cadastrarS.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        
        if (model == null) {
            model = (DefaultTableModel) tblSugestoes.getModel();
        }
        atualizarTabela();

    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvaliacoes;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnPacotes;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImagem2;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblmagem;
    private javax.swing.JTable tblSugestoes;
    private javax.swing.JTextField txtSugestoes;
    // End of variables declaration//GEN-END:variables

    private void atualizarTabela() {
      
        model.setRowCount(0);
        SugestaoDao dao = new SugestaoDao();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");

        // Recuperando as sugestões e adicionando na tabela
        for (Sugestao s : dao.getSugestoes()) {
            model.addRow(new Object[]{
                s.getId(), 
                s.getNome(), 
                s.getDataHora().format(formatter), 
                s.getDescricao()
            });
        }
    }
    
    public void configurarBotoesPorTipoUsuario(Usuario u) {
    
    if (u.getTipo().equalsIgnoreCase("Administrador")) {
        btnCadastro.setEnabled(true);
    } else if (u.getTipo().equalsIgnoreCase("usuario")) {
        btnCadastro.setEnabled(false);
        btnCadastro.setVisible(false);
    } else {
       
        btnCadastro.setVisible(false);
        btnCadastro.setEnabled(false);
    }
 }
}
