/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Dao.CadastrarDao;
import br.com.senac.servicostreaming.model.Conteudo;
import br.com.senac.servicostreaming.model.Usuario;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Duwann
 */
public class Lista extends javax.swing.JFrame {

    private Usuario usuario;
    
    public Lista(){
    initComponents();
    }
    
    public Lista(Usuario u){
        
        initComponents();
        this.usuario = u;
        configurarBotoesPorTipoUsuario(usuario);
     
       if (usuario != null) {
           lblUsuario.setText(usuario.getNome());
       } else {
           lblUsuario.setText("Usuário não identificado");
       }
         preencherTabela();
   
    }
    
      private void preencherTabela() {
                CadastrarDao cadastrarDao = new CadastrarDao();
            
                String titulo = txtBusca.getText();
                
                List<Conteudo> listaConteudos = cadastrarDao.getConteudos(titulo);
            
                DefaultTableModel tabelaListagem = (DefaultTableModel) tblListagem.getModel();
                
                //linha filtro dinâmico
                tabelaListagem.setNumRows(0);

                 TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(tabelaListagem);
                 tblListagem.setRowSorter(sorter);
                      
                for (Conteudo c : listaConteudos) { 
                    Object[] obj = new Object[] { 
                        c.getId(),           
                        c.getTitulo(), 
                        c.getTipoConteudo(),
                        c.getQuantiEpisodios(),
                        c.getDataLancamento(),
                        c.getAutor(),
                        c.getDescricao(),
                    };
                    tabelaListagem.addRow(obj);
                }    
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lblImagem3 = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        btnAvaliacoes = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        btnPacotes = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListagem = new javax.swing.JTable();
        btnCadastro = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 39, 52));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("SansSerif", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Lista de Animes,Filmes e etc");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 260, -1));

        lblImagem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/0e65d4a0-5271-4bd6-9ed0-a43e6f529604.jpg"))); // NOI18N
        jPanel1.add(lblImagem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 530, 30));

        txtBusca.setBackground(new java.awt.Color(51, 51, 51));
        txtBusca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBusca.setForeground(new java.awt.Color(255, 255, 255));
        txtBusca.setToolTipText("Escreva o nome do conteúdo que quer procura");
        txtBusca.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtBuscaCaretUpdate(evt);
            }
        });
        txtBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaActionPerformed(evt);
            }
        });
        jPanel1.add(txtBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 500, 30));

        btnAvaliacoes.setBackground(new java.awt.Color(24, 61, 128));
        btnAvaliacoes.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnAvaliacoes.setForeground(new java.awt.Color(255, 255, 255));
        btnAvaliacoes.setText("Avaliações");
        btnAvaliacoes.setContentAreaFilled(false);
        btnAvaliacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvaliacoesActionPerformed(evt);
            }
        });
        jPanel1.add(btnAvaliacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 120, 20));

        btnHome.setBackground(new java.awt.Color(24, 61, 128));
        btnHome.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Home");
        btnHome.setContentAreaFilled(false);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 100, 20));

        btnLista.setBackground(new java.awt.Color(24, 61, 128));
        btnLista.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnLista.setForeground(new java.awt.Color(255, 255, 255));
        btnLista.setText("Lista");
        btnLista.setContentAreaFilled(false);
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });
        jPanel1.add(btnLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 80, 20));

        btnPacotes.setBackground(new java.awt.Color(24, 61, 128));
        btnPacotes.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnPacotes.setForeground(new java.awt.Color(255, 255, 255));
        btnPacotes.setText("Pacotes");
        btnPacotes.setContentAreaFilled(false);
        btnPacotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacotesActionPerformed(evt);
            }
        });
        jPanel1.add(btnPacotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 120, 20));

        jLabel6.setFont(new java.awt.Font("SansSerif", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Buscar por Nome:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        tblListagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Tipo", "Episódios", "Data Lançamento", "Autor", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListagem);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 780, 430));

        btnCadastro.setBackground(new java.awt.Color(24, 61, 128));
        btnCadastro.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnCadastro.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastro.setText("Cadastrar Conteúdos");
        btnCadastro.setContentAreaFilled(false);
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 210, 20));

        lblUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaActionPerformed

    private void btnAvaliacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvaliacoesActionPerformed
        
        Avaliacao avaliacao = new Avaliacao(usuario);
        avaliacao.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnAvaliacoesActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        
        Home home = new Home(usuario);
        home.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListaActionPerformed

    private void btnPacotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacotesActionPerformed
       
        Pacote pacote = new Pacote(usuario);
        pacote.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnPacotesActionPerformed

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        
        CadastrarS cadastrarS = new CadastrarS(usuario);
        cadastrarS.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

 
    }//GEN-LAST:event_formWindowGainedFocus

    private void txtBuscaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtBuscaCaretUpdate
        preencherTabela();
    }//GEN-LAST:event_txtBuscaCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvaliacoes;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnPacotes;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImagem3;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTable tblListagem;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables

    public void configurarBotoesPorTipoUsuario(Usuario u) {
    
    if (u.getTipo().equalsIgnoreCase("Administrador")) {
        btnCadastro.setEnabled(true);
    } else if (u.getTipo().equalsIgnoreCase("usuario")) {
        btnCadastro.setEnabled(false);
        btnCadastro.setVisible(false);
    } else {
       
        btnCadastro.setVisible(false);
        btnCadastro.setEnabled(false);
    }
 }
}
