/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Conexao.Conexao;
import Dao.UserDao;
import Persistence.Criptografia;
import br.com.senac.servicostreaming.model.Usuario;
import com.sun.jdi.connect.spi.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Duwann
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnLogin1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblImagem1 = new javax.swing.JLabel();
        lblImagem2 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(26, 26, 26));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("SansSerif", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cadastre-se e faça parte!");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 2, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Não possui uma conta?");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Senha:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, -1, 20));

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail.setToolTipText("Insira o seu email(Conta adm: admin@gmail.com )");
        txtEmail.setNextFocusableComponent(txtSenha);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 260, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, 20));

        btnCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setToolTipText("Botão para a tela de cadastro");
        btnCadastrar.setNextFocusableComponent(txtEmail);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 120, 30));

        btnLogin1.setBackground(new java.awt.Color(24, 61, 128));
        btnLogin1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnLogin1.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin1.setText("Login");
        btnLogin1.setToolTipText("Botão de login");
        btnLogin1.setNextFocusableComponent(btnCadastrar);
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 410, 120, 30));

        jLabel5.setFont(new java.awt.Font("SansSerif", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Faça o seu login");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, -1, -1));

        lblImagem1.setBackground(new java.awt.Color(24, 61, 128));
        lblImagem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/d0f6973a-fb35-4b2f-a591-6be500acbdcd.jpg"))); // NOI18N
        jPanel1.add(lblImagem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 430, -1));

        lblImagem2.setBackground(new java.awt.Color(24, 61, 128));
        lblImagem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/d0f6973a-fb35-4b2f-a591-6be500acbdcd.jpg"))); // NOI18N
        jPanel1.add(lblImagem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 420, -1));

        txtSenha.setBackground(new java.awt.Color(255, 255, 255));
        txtSenha.setToolTipText("Insira a senha (senha do adm: 1234)");
        txtSenha.setNextFocusableComponent(btnLogin1);
        jPanel1.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 260, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        
        Cadastro cadastro = new Cadastro();
        cadastro.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
       
          if (!ValidacaoDados()) {
            return;  
        }
          
        UserDao dao = new UserDao();
        Usuario u = new Usuario();
        Conexao c = new Conexao();
        java.sql.Connection status = c.conectar();
       
        if (status == null) {
            JOptionPane.showMessageDialog(null, "Erro de conexão");
        }
        
        u.setEmail(txtEmail.getText().trim());
        u.setSenha(Criptografia.getMD5(txtSenha.getText().trim()));
        
        u = dao.validar(u);
        
        if(u!=null){
            
            JOptionPane.showMessageDialog(null, "Olá usuário, sua permissão é de " + u.getTipo() + ". Seja bem-vindo!", "Sucesso",
                    JOptionPane.INFORMATION_MESSAGE);
            
            if (u.getTipo().equalsIgnoreCase("Administrador")) {
                CadastrarS cadastrar = new CadastrarS(u);
                cadastrar.setVisible(true);
                this.dispose();
            } else {
                Home home = new Home(u);
                home.setVisible(true);
                this.dispose();
            }
            txtEmail.setText("");
            txtSenha.setText("");
        } else {
            JOptionPane.showMessageDialog(null,"⚠ Usuário não encontrado.Login ou senha estão errados.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }  
        
        dao.desconectar();
        
    }//GEN-LAST:event_btnLogin1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLogin1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImagem1;
    private javax.swing.JLabel lblImagem2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

 private boolean ValidacaoDados() {
     
        try {
            if (txtSenha.getText().isEmpty() || txtEmail.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "⚠ Preencha todos os campos.","Erro", JOptionPane.ERROR_MESSAGE);
                return false;
            }

        } catch (Exception e) {
            // Tratamento genérico para outros erros inesperados
            javax.swing.JOptionPane.showMessageDialog(this, "Ocorreu um erro: " + e.getMessage(), "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }

}
    
