/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Conexao.Conexao;
import Dao.CartaoDao;
import Dao.PacoteDao;
import Dao.UserDao;
import br.com.senac.servicostreaming.model.Cartao;
import br.com.senac.servicostreaming.model.PacoteM;
import br.com.senac.servicostreaming.model.Usuario;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Duwann
 */
public class Pacote extends javax.swing.JFrame {

    private Usuario usuario;
    private Cartao cartao;
    private PacoteM pacote;
    
    public Pacote() {
        initComponents();
    }
    
      public Pacote(Usuario u) {
        initComponents();
        this.usuario = u;
        configurarBotoesPorTipoUsuario(usuario);
     
       if (usuario != null) {
           lblUsuario.setText(usuario.getNome());
       } else {
           lblUsuario.setText("Usuário não identificado");
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnComprar = new javax.swing.JButton();
        txtCpf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtValidade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblImagem3 = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        btnAvaliacoes = new javax.swing.JButton();
        btnCadastro = new javax.swing.JButton();
        btnPacotes1 = new javax.swing.JButton();
        cboxPacote = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cboxPagamento = new javax.swing.JComboBox<>();
        lblUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(36, 39, 52));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("SansSerif", 2, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Adicione novos conteúdos ao sistema.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 410, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome completo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, -1, 20));

        txtNome.setBackground(new java.awt.Color(51, 51, 51));
        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNome.setForeground(new java.awt.Color(255, 255, 255));
        txtNome.setToolTipText("Insira o seu nome");
        txtNome.setNextFocusableComponent(txtCpf);
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 420, 30));

        txtCodigo.setBackground(new java.awt.Color(51, 51, 51));
        txtCodigo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigo.setToolTipText("Insira o código de segurança (de 3 a 4 dígitos)");
        txtCodigo.setNextFocusableComponent(txtNome);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 200, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Código de segurança:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, -1, 20));

        btnComprar.setBackground(new java.awt.Color(24, 61, 128));
        btnComprar.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnComprar.setForeground(new java.awt.Color(255, 255, 255));
        btnComprar.setText("Comprar");
        btnComprar.setNextFocusableComponent(txtNumero);
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });
        jPanel1.add(btnComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 120, 30));

        txtCpf.setBackground(new java.awt.Color(51, 51, 51));
        txtCpf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCpf.setForeground(new java.awt.Color(255, 255, 255));
        txtCpf.setToolTipText("Insira o seu CPF ( 123.123.123-12)");
        txtCpf.setNextFocusableComponent(txtTelefone);
        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });
        jPanel1.add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 410, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CPF:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, -1, 20));

        txtValidade.setBackground(new java.awt.Color(51, 51, 51));
        txtValidade.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtValidade.setForeground(new java.awt.Color(255, 255, 255));
        txtValidade.setToolTipText("Insira a validade do cartão (mm/aaaa)");
        txtValidade.setNextFocusableComponent(txtCodigo);
        txtValidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValidadeActionPerformed(evt);
            }
        });
        jPanel1.add(txtValidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 200, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("validade:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Pacotes:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, 20));

        txtNumero.setBackground(new java.awt.Color(51, 51, 51));
        txtNumero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNumero.setForeground(new java.awt.Color(255, 255, 255));
        txtNumero.setToolTipText("Insira o numero do cartão");
        txtNumero.setNextFocusableComponent(txtValidade);
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 420, 30));

        lblImagem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/0e65d4a0-5271-4bd6-9ed0-a43e6f529604.jpg"))); // NOI18N
        jPanel1.add(lblImagem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 530, 30));

        btnHome.setBackground(new java.awt.Color(24, 61, 128));
        btnHome.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("Home");
        btnHome.setContentAreaFilled(false);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 100, 20));

        btnLista.setBackground(new java.awt.Color(24, 61, 128));
        btnLista.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnLista.setForeground(new java.awt.Color(255, 255, 255));
        btnLista.setText("Lista");
        btnLista.setContentAreaFilled(false);
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });
        jPanel1.add(btnLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 80, 20));

        btnAvaliacoes.setBackground(new java.awt.Color(24, 61, 128));
        btnAvaliacoes.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnAvaliacoes.setForeground(new java.awt.Color(255, 255, 255));
        btnAvaliacoes.setText("Avaliações");
        btnAvaliacoes.setContentAreaFilled(false);
        btnAvaliacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvaliacoesActionPerformed(evt);
            }
        });
        jPanel1.add(btnAvaliacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 120, 20));

        btnCadastro.setBackground(new java.awt.Color(24, 61, 128));
        btnCadastro.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnCadastro.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastro.setText("Cadastrar Conteúdos");
        btnCadastro.setContentAreaFilled(false);
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 210, 20));

        btnPacotes1.setBackground(new java.awt.Color(24, 61, 128));
        btnPacotes1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        btnPacotes1.setForeground(new java.awt.Color(255, 255, 255));
        btnPacotes1.setText("Pacotes");
        btnPacotes1.setContentAreaFilled(false);
        btnPacotes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPacotes1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPacotes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 120, 20));

        cboxPacote.setBackground(new java.awt.Color(51, 51, 51));
        cboxPacote.setForeground(new java.awt.Color(255, 255, 255));
        cboxPacote.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pacote 1", "Pacote 2", "Pacote 3" }));
        cboxPacote.setToolTipText("Escolha o pacote");
        cboxPacote.setNextFocusableComponent(cboxPagamento);
        jPanel1.add(cboxPacote, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 140, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Número do cartão:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, -1, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Telefone:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, -1, 20));

        txtTelefone.setBackground(new java.awt.Color(51, 51, 51));
        txtTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTelefone.setForeground(new java.awt.Color(255, 255, 255));
        txtTelefone.setToolTipText("Insira o seu número de telefone(+55 11 12345-1234)");
        txtTelefone.setNextFocusableComponent(txtData);
        txtTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 510, 200, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data de nascimento:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, -1, 20));

        txtData.setBackground(new java.awt.Color(51, 51, 51));
        txtData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtData.setForeground(new java.awt.Color(255, 255, 255));
        txtData.setToolTipText("Insira a sua data de nascimento(dd/mm/aaaa)");
        txtData.setNextFocusableComponent(cboxPacote);
        txtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataActionPerformed(evt);
            }
        });
        jPanel1.add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, 200, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Forma de pagamento:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, 20));

        cboxPagamento.setBackground(new java.awt.Color(51, 51, 51));
        cboxPagamento.setForeground(new java.awt.Color(255, 255, 255));
        cboxPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Débito", "Crédito" }));
        cboxPagamento.setToolTipText("Escoha a forma de pagamento");
        cboxPagamento.setNextFocusableComponent(btnComprar);
        cboxPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxPagamentoActionPerformed(evt);
            }
        });
        jPanel1.add(cboxPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 140, -1));

        lblUsuario.setBackground(new java.awt.Color(255, 255, 255));
        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
    if (!ValidacaoDados()) {
        return;  
        }    
        
    PacoteDao pDao = new PacoteDao();
    UserDao dao = new UserDao();
    Conexao c = new Conexao();
             
    java.sql.Connection status = c.conectar();  
    
    if (status == null) {
            JOptionPane.showMessageDialog(null, "Erro de conexão");
        }
        
    String pacoteSelecionado = cboxPacote.getSelectedItem().toString();
    
    pacote = pDao.buscarPacotePorNome(pacoteSelecionado);

    if (pacote == null) {
        JOptionPane.showMessageDialog(null, "Pacote não encontrado!");
        return;
    }

    int resposta = JOptionPane.showConfirmDialog(
    null, 
    "O preço do " + pacote.getNome() + " é R$ " + pacote.getValor() + ".\nDeseja realmente comprar?", 
    "Confirmação de Compra", 
    JOptionPane.YES_NO_OPTION
 );
    
    if (resposta == JOptionPane.YES_OPTION) { 
        
    int idUsuario = usuario.getId();
    Usuario usuarioRecuperado = dao.buscarPorId(idUsuario);
    
    if (usuarioRecuperado == null) {
    JOptionPane.showMessageDialog(null, "Usuário não encontrado. Insira um cartão apenas para usuários existentes.");
    return; // Interrompe a operação se o usuário não existir
}
        
    String numeroCartao = txtNumero.getText();
    String nomeTitular = txtNome.getText();
    String validade = txtValidade.getText();
    String codigoSeguranca = txtCodigo.getText();
    String pagamento = cboxPagamento.getSelectedItem().toString();
    
    usuario.setPossuiPacote("Sim");
    
    int idPacote = pacote.getId();
    PacoteM p = pDao.buscarPorId(idPacote);
    usuario.setPacote(p);

    // Criar objeto Cartao e PacoteCartao

    Cartao cartao = new Cartao();
    
    cartao.setNomeTitular(nomeTitular);
    cartao.setNumero(numeroCartao);
    cartao.setValidade(validade);
    cartao.setCodigoSeguranca(codigoSeguranca);
    cartao.setTipo(pagamento);
    cartao.setUsuario(usuarioRecuperado);
    
    CartaoDao cartaoDAO = new CartaoDao();

        int statusCartao = cartaoDAO.addCartao(cartao);
        boolean statusUsuario = dao.atualizar(pacote,usuarioRecuperado);
        
        if (statusCartao == 1 && statusUsuario) {
            JOptionPane.showMessageDialog(null, "Compra realizada com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao processar a compra!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        
        } else {
            JOptionPane.showMessageDialog(null, "Compra cancelada.");
        }

        dao.desconectar();
    }//GEN-LAST:event_btnComprarActionPerformed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void txtValidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValidadeActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed

        Home home = new Home(usuario);
        home.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed

        Lista lista = new Lista(usuario);
        lista.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnListaActionPerformed

    private void btnAvaliacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvaliacoesActionPerformed

        Avaliacao avaliacao = new Avaliacao(usuario);
        avaliacao.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnAvaliacoesActionPerformed

    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        
        CadastrarS cadastrarS = new CadastrarS(usuario);
        cadastrarS.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void btnPacotes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacotes1ActionPerformed

    }//GEN-LAST:event_btnPacotes1ActionPerformed

    private void txtTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneActionPerformed

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void cboxPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxPagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pacote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pacote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pacote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pacote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pacote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvaliacoes;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnPacotes1;
    private javax.swing.JComboBox<String> cboxPacote;
    private javax.swing.JComboBox<String> cboxPagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblImagem3;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtValidade;
    // End of variables declaration//GEN-END:variables

public void configurarBotoesPorTipoUsuario(Usuario u) {
    
    if (u.getTipo().equalsIgnoreCase("Administrador")) {
        btnCadastro.setEnabled(true);
    } else if (u.getTipo().equalsIgnoreCase("usuario")) {
        btnCadastro.setEnabled(false);
        btnCadastro.setVisible(false);
    } else {
       
        btnCadastro.setVisible(false);
        btnCadastro.setEnabled(false);
    }
 }

private boolean ValidacaoDados() {

    // Expressões regulares para validar formatos
    boolean validadeB = txtValidade.getText().matches("[0-9]{2}/[0-9]{4}");
    boolean cpfB = txtCpf.getText().matches("\\d{11}|\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}");
    boolean telefoneB = txtTelefone.getText().matches("\\+55\\s?\\d{2}\\s?\\d{5}-\\d{4}");
    boolean dataNascimentoB = txtData.getText().matches("\\d{2}/\\d{2}/\\d{4}");

    try {
        // Verifica se todos os campos foram preenchidos
        if (txtNumero.getText().isEmpty() ||
            txtValidade.getText().isEmpty() ||
            txtCodigo.getText().isEmpty() ||
            txtNome.getText().isEmpty() ||
            txtCpf.getText().isEmpty() ||
            txtTelefone.getText().isEmpty() ||
            txtData.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "⚠ Preencha todos os campos.", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        if (!txtNumero.getText().matches("\\d{1,19}")) {
            JOptionPane.showMessageDialog(null, "⚠ Número do cartão inválido! Deve conter apenas números (1 a 19 dígitos).", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (!txtCodigo.getText().matches("\\d{3,4}")) {
            JOptionPane.showMessageDialog(null, "⚠ Código de segurança inválido! Deve conter apenas números (3 ou 4 dígitos).", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        if (!validadeB) {
            JOptionPane.showMessageDialog(null, "⚠ Validade deve estar no formato MM/AAAA.", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            String[] partes = txtValidade.getText().split("/");
            int mes = Integer.parseInt(partes[0]);
            int ano = Integer.parseInt(partes[1]);

            if (mes < 1 || mes > 12) {
                JOptionPane.showMessageDialog(null, "⚠ Mês inválido! Deve estar entre 01 e 12.", "Erro", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
        
        if (!cpfB) {
            JOptionPane.showMessageDialog(null, "⚠ CPF inválido! Deve estar no formato 000.000.000-00 ou apenas números.", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        if (!telefoneB) {
            JOptionPane.showMessageDialog(null, "⚠ Telefone inválido! Deve ser no formato +55 11 94400-5908.", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        if (!dataNascimentoB) {
            JOptionPane.showMessageDialog(null, "⚠ Data de nascimento inválida! Deve estar no formato DD/MM/AAAA.", "Erro", JOptionPane.ERROR_MESSAGE);
            return false;
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Ocorreu um erro: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    return true;
 }
    
}
